retaildevcrews/ngsa-asb

deploy/ngsaprec/config.json
To create deployment folder and config for central preprod cluster
- References https://github.com/retaildevcrews/wcnp/issues/373
=> Added central preprod cluster

deploy/ngsadev/config.json, deploy/ngsaprec/config.json
References https://github.com/retaildevcrews/loderunner/pull/50
=> Update config.json to include loderunner

README.md, deploy/ngsadev/istio/istio-gateway.yaml, deploy/ngsaprec/istio/istio-gateway.yaml, docs/deployNgsaYaml.md, templates/istio-gateway.yaml
Multiple istio gateways cannot use the same host so let's use a single one for the whole cluster
Update templates/ documentation to support updated istio file
Change ngsadev and ngsaprec installations
=> Single istio gateway for entire cluster

README.md, cluster-stamp.json
Use single LA workspace for all clusters
- Closes  https://github.com/retaildevcrews/wcnp/issues/440
=> Add functionality for re-using an existing log analytics workspace

deploy/ngsadev/monitoring/03-grafana.yaml, deploy/ngsadev/monitoring/04-grafana-pod-identity.yaml, deploy/ngsaprec/monitoring/03-grafana.yaml, deploy/ngsaprec/monitoring/04-grafana-pod-identity.yaml, monitoring/README.md, templates/grafana-aad.yaml, templates/grafana-pod-identity.yaml, templates/ngsa-cosmos.yaml, templates/ngsa-java.yaml, templates/ngsa-memory.yaml
Enable Grafana AAD Auth on both NGSA environments
Added Grafana AAD auth setup steps monitoring docs
=> Grafana aad

monitoring/dashboards/ngsa-pre-model.json
Adding the preprod Grafana dashboard json model in repo
=> Add preprod dashboard json

deploy/ngsadev/monitoring/03-grafana.yaml, deploy/ngsaprec/monitoring/03-grafana.yaml, monitoring/README.md, templates/grafana-aad.yaml
Enforce grafana AAD authorization by checking users for AAD group membership
=> Add Grafana authorization

monitoring/dashboards/ngsa-dev-model.json
To fix the broken grafana dashboards in dev environment
- Closes https://github.com/retaildevcrews/wcnp/issues/486
=> Fixed Grafana Dashboards for dev environment

docs/deployAdditionalCluster.md
Added instructions to ASB docs for Firewall Changes When Deploying Additional Clusters
- Closes https://github.com/retaildevcrews/wcnp/issues/567
=> Added instructions to update Hub Firewall Policy Network Rules

README.md, deploy/pre-ngsa-asb-eastus/fluentbit/01-namespace.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/02-config.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/03-config-log.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/04-role.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-eastus/istio/istio-gateway.yaml, deploy/pre-ngsa-asb-eastus/istio/istio-ingress.yaml, deploy/pre-ngsa-asb-eastus/istio/istio-pod-identity-config.yaml, deploy/pre-ngsa-asb-eastus/loderunner/loderunner.yaml, deploy/pre-ngsa-asb-eastus/monitoring/01-namespace.yaml, deploy/pre-ngsa-asb-eastus/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-eastus/monitoring/03-grafana.yaml, deploy/pre-ngsa-asb-eastus/monitoring/04-grafana-pod-identity.yaml, deploy/pre-ngsa-asb-eastus/ngsa/ngsa-cosmos.yaml, deploy/pre-ngsa-asb-eastus/ngsa/ngsa-java.yaml, deploy/pre-ngsa-asb-eastus/ngsa/ngsa-memory.yaml, deploy/pre-ngsa-asb-eastus/ngsa/ngsa-pod-identity.yaml, docs/cosmos.md, docs/deployNgsaYaml.md, monitoring/README.md, monitoring/dashboards/ngsa-pre-model.json
These are the updates to docs and config files from setting up the preprod hub and first spoke. All yaml and json files are generated automatically while following the setup instructions. Only the markdown files were updated with doc updates. The preprod environment is not finished, but this is a good stopping point to open a PR with changes to the first set of docs.
App URLS
- https://ngsa-memory-eastus-pre.cse.ms/version
- https://ngsa-cosmos-eastus-pre.cse.ms/version
- https://ngsa-java-eastus-pre.cse.ms/version
- https://grafana-eastus-pre.cse.ms/
- References https://github.com/retaildevcrews/wcnp/issues/573
=> Doc updates and config for setting up preprod hub and first spoke

deploy/pre-ngsa-asb-centralus/config.json, deploy/pre-ngsa-asb-eastus/config.json, deploy/pre-ngsa-asb-westus2/config.json
Adding autogitops config files for the new preprod environments.
- References https://github.com/retaildevcrews/wcnp/issues/573
=> adding config files for autogitops

deploy/dev-ngsa-asb-eastus/monitoring/02-prometheus.yaml, deploy/dev-ngsa-asb-westus2/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-centralus/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-eastus/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-westus2/monitoring/02-prometheus.yaml, monitoring/README.md, templates/monitoring/02-prometheus.yaml
Prometheus pods are running out of memory in environment, reducing the memory usage
- by increasing scrape interval to 15s
- enforcing metric retention time to 3d
Add note in documentation about OOM issue faced and temporary fix
- References #638
=> Reduce prometheus memory usage

deploy/dev-ngsa-asb-eastus/istio/istio-gateway.yaml, templates/istio/istio-gateway.yaml
Add loderunner to the Istio gateway template
- Closes #issue_number (this will automatically close the issue when the PR closes)
- References https://github.com/retaildevcrews/wcnp/issues/663
=> Add loderunner to the Istio gateway template

deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml, deploy/dev-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor.yaml, deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml, deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml, deploy/pre-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor.yaml, monitoring/dashboards/ngsa-dev-model.json, monitoring/dashboards/ngsa-pre-model.json
To update Grafana Dashboards to support multi-region view
- Closes https://github.com/retaildevcrews/wcnp/issues/717
=> Update Grafana Dashboards to support multi-region view

monitoring/alerts/metricsAlerts/dev/asb-dev-eastus-AppEndpointDown.json, monitoring/alerts/metricsAlerts/dev/asb-dev-westus2-AppEndpointDown.json, monitoring/alerts/metricsAlerts/pre/asb-pre-centralus-AppEndpointDown.json, monitoring/alerts/metricsAlerts/pre/asb-pre-eastus-AppEndpointDown.json, monitoring/alerts/metricsAlerts/pre/asb-pre-westus2-AppEndpointDown.json
Renamed App gateway down alerts to be more specific -> App endpoint alerts
Added LR UI endpoints in dev alerts config
- Closes https://github.com/retaildevcrews/wcnp/issues/718
=> Change app gateway alert definition

README.md, docs/deployNgsaAgo.md, docs/deployNgsaYaml.md
To reference the autogitops documentation and get rid of TODOs
- Closes https://github.com/retaildevcrews/wcnp/issues/736
=> Updated NGSA-ASB docs

networking/hub-regionA.json
- Update hub-regionA.json to be inline with file in ngsa-asb repo.
- Add firewall policy to allow traffic to LR
- Closes https://github.com/retaildevcrews/wcnp/issues/728
- References https://github.com/retaildevcrews/wcnp/issues/727
- References https://github.com/retaildevcrews/wcnp/issues/333
=> FirewallPolicy, ruleCollectionGroup for *-dev.cse.ms

deploy/dev-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml, deploy/dev-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml, deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-blocked-traffic.yaml, deploy/pre-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml, deploy/pre-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml, deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-blocked-traffic.yaml, monitoring/README.md
- add grafana dashboard json for blocked network traffic
- update grafana configs and deployments to load the new dashboard with gitops
- example: https://grafana-eastus-pre.cse.ms/d/PpsPzW8nk/ngsa-pre-blocked-traffic?orgId=1&from=now-30d&to=now
- Closes https://github.com/retaildevcrews/wcnp/issues/731
=> Blocked network traffic Grafana dashboard

deploy/bootstrap/istio/02-istio-operator.yaml, deploy/dev-ngsa-asb-westus2/burst/burst-metrics-service.yaml
Checkov linter fixes and rule exceptions (with explanations) for istio, burst service
- Closes https://github.com/retaildevcrews/wcnp/issues/790
=> Checkov linter fixes for istio, burst service

deploy/dev-ngsa-asb-eastus/fluentbit/02-config.yaml, deploy/dev-ngsa-asb-eastus/istio/istio-ingress.yaml, deploy/dev-ngsa-asb-eastus/ngsa/namespace.yaml, deploy/dev-ngsa-asb-westus2/fluentbit/02-config.yaml, deploy/dev-ngsa-asb-westus2/istio/istio-ingress.yaml, templates/fluentbit/config.yaml, templates/istio/istio-ingress.yaml, templates/ngsa/namespace.yaml
- Closes https://github.com/retaildevcrews/wcnp/issues/789
=> Enable Istio logs and making it part of our standard build

deploy/dev-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/dev-ngsa-asb-westus2/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-centralus/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-westus2/fluentbit/05-daemonset.yaml, templates/fluentbit/daemonset.yaml
Checkov fluentbit fixes
- References https://github.com/retaildevcrews/wcnp/issues/845
=> Checkov fluentbit fixes

deploy/bootstrap/cluster-baseline-settings/05-kured.yaml
Checkov fixes for kured
- Closes https://github.com/retaildevcrews/wcnp/issues/792
=> Checkov fixes for kured

deploy/dev-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml, deploy/dev-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml, deploy/pre-ngsa-asb-centralus/monitoring/grafana/05-grafana.yaml, deploy/pre-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml, deploy/pre-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml, monitoring/README.md, templates/monitoring/03-grafana-aad.yaml
Upgrade version of grafana currently deployed in clusters
- Closes https://github.com/retaildevcrews/wcnp/issues/846
=> Upgrade grafana version in env

deploy/dev-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/dev-ngsa-asb-westus2/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-centralus/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-westus2/fluentbit/05-daemonset.yaml, templates/fluentbit/daemonset.yaml
Kubernetes log annotations are currently missing from the logs. Making the fix in fluentbit
- References https://github.com/retaildevcrews/wcnp/issues/845
=> Fix fluentbit kubectl log annotations

deploy/dev-ngsa-asb-eastus/istio/istio-ingress.yaml, deploy/dev-ngsa-asb-westus2/istio/istio-ingress.yaml, monitoring/alerts/README.md, monitoring/alerts/scheduledQueries/dev/Burst-Header-Failures.json
Add Burst header in ingress log (where available)
Create a new alert rule to verify that burst headers are returned on requests to NGSA
- Closes https://github.com/retaildevcrews/wcnp/issues/764
=> Add burst header monitoring

README.md
Documented Fluentbit is sending random duplicate logs to Log Analytics
- Closes # https://github.com/retaildevcrews/wcnp/issues/750
=> Documented Fluentbit is sending random duplicate logs to Log Analytics

deploy/dev-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/dev-ngsa-asb-westus2/fluentbit/05-daemonset.yaml
Upgrade fluentbit from 1.5 to 1.9.5 to fix issue where log files are reprocessed when a pod restarts.
- References https://github.com/retaildevcrews/wcnp/issues/854
=> upgrade dev fluentbit from 1.5 to 1.9.5

.gitignore, .vscode/tasks.json, README.md
Add Checkov VS code Task to Codespaces and populate a summary section at the end.
- Closes https://github.com/retaildevcrews/wcnp/issues/848
- Closes https://github.com/retaildevcrews/wcnp/issues/909
=> Add Checkov VS code Task to Codespaces and populate a summary section.

spikes/harbor/README.md, spikes/harbor/gen-multi-domain-certs.bash, spikes/harbor/harbor-virtual-svc.yaml, spikes/harbor/harbor.yml, spikes/harbor/helm-values.yaml
> Moved from https://github.com/retaildevcrews/istio/pull/68
SPIKE: Setting up Harbor in AKS and local cluster
With documentation and diagrams: Check the [mermaid diagrams in README](https://github.com/retaildevcrews/istio/tree/spike/harbor/spikes/harbor)
- Closes https://github.com/retaildevcrews/wcnp/issues/793
=> Harbor Spike

README.md
Add documentation for Azure resource locks.
- Closes https://github.com/retaildevcrews/wcnp/issues/915
=> Add documentation for Azure resource locks

README.md, deploy/dev-ngsa-asb-eastus/loderunner/dev/loderunner/loderunner-pod-identity.yaml, deploy/dev-ngsa-asb-westus2/loderunner/dev/loderunner/loderunner-pod-identity.yaml, docs/deployLodeRunnerYaml.md, docs/deployNgsaYaml.md, templates/loderunner/loderunner-api.yaml, templates/loderunner/loderunner-clientmode.yaml, templates/loderunner/loderunner-commandmode.yaml, templates/loderunner/loderunner-pod-identity.yaml, templates/loderunner/loderunner-ui.yaml
Add documentation on how to deploy loderunner api and loderunner ui in ngsa-asb
- Closes https://github.com/retaildevcrews/wcnp/issues/919
- Dependent PR: https://github.com/retaildevcrews/loderunner/pull/295
=> Add documentation on how to deploy loderunner api and loderunner ui in ngsa-asb

README.md, cluster/cluster-stamp-additional.json, cluster/cluster-stamp.json, docs/disableWAFconfig.md
Document how to disable WAF-config
- Closes https://github.com/retaildevcrews/wcnp/issues/938
- References https://github.com/retaildevcrews/wcnp/issues/919
=>  Document how to disable WAF-config

README.md
Automatically check if user is present in aad group (returns true/false, rather than manually seeing entry match)
- Closes #939
=> AAD check will now validate if user is present automatically

deploy/dev-ngsa-asb-westus2/burst/remote-filter-ngsa-cosmos.yaml, templates/burst/remote-filter.yaml
Changed the wasm binary file, SHA must be updated to the latest copy
- References #99
=> Update sha for latest WASM binary

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/on-create.sh
NGSA asb now uses the weekly cse-labs:k3d image as a base
devcontainer now supports flux v5+, k8s version > 1.22
- Closes https://github.com/retaildevcrews/wcnp/issues/910
=> Update ASB devcontainer 

deploy/bootstrap/flux-system/gotk-repo.yaml, deploy/dev-bootstrap/flux-system/gotk-repo.yaml, deploy/dev-ngsa-asb-eastus/monitoring/02-prometheus.yaml, deploy/dev-ngsa-asb-westus2/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-centralus/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-eastus/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-westus2/monitoring/02-prometheus.yaml, docs/cloudshell.txt, monitoring/README.md, spikes/thanos/manifests/observee/prometheus/prometheus.yaml, spikes/thanos/manifests/observer/prometheus/prometheus.yaml, templates/monitoring/02-prometheus.yaml
To fix issue regarding prometheus PVC
- Closes https://github.com/retaildevcrews/wcnp/issues/930
=> Fixed Prometheus PVC issues

deploy/dev-ngsa-asb-westus2/burst/remote-filter-ngsa-cosmos.yaml
Wasm plugin has been updated with a new version, we need to adjust the sha256 value in the filter config accordingly
- References https://github.com/retaildevcrews/wcnp/issues/997
=> Adjust wasm sha to latest version

.github/workflows/README.md, README.md, docs/cosmos.md, monitoring/README.md
Use id instead of object id in az ad commands
- Closes https://github.com/retaildevcrews/wcnp/issues/1007
=> Fix id query step

deploy/bootstrap-pre/cluster-baseline-settings/cluster-baseline-flux-kustomization.yaml
Fixing an issue with wrong directory being referenced in bootstrap directory
=> fixing path

flux-init/init-dev/gotk-components-dev.yaml, flux-init/init-preprod/gotk-components-pre.yaml, flux-init/init-preprod/gotk-repo.yaml
To update the cpu and memory resource
- Closes https://github.com/retaildevcrews/wcnp/issues/1018
- References https://github.com/retaildevcrews/wcnp/issues/1001
=> Update Memory and CPU for Flux deployments

deploy/dev-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/dev-ngsa-asb-eastus/monitoring/02-prometheus.yaml, deploy/dev-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml, deploy/dev-ngsa-asb-westus2/fluentbit/05-daemonset.yaml, deploy/dev-ngsa-asb-westus2/monitoring/02-prometheus.yaml, deploy/dev-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml, deploy/pre-ngsa-asb-centralus/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-centralus/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-centralus/monitoring/grafana/05-grafana.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-eastus/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml, deploy/pre-ngsa-asb-westus2/fluentbit/05-daemonset.yaml, deploy/pre-ngsa-asb-westus2/monitoring/02-prometheus.yaml, deploy/pre-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml, flux-init/init-preprod/gotk-repo.yaml, templates/fluentbit/05-daemonset.yaml
- Closes https://github.com/retaildevcrews/wcnp/issues/1017
=> Fluentbit, Grafana, Prometheus Bash Pod Resource Changes

spikes/harbor/helm-values.yaml
- References https://github.com/retaildevcrews/wcnp/issues/1017
=> Harbor Resource Bash Changes

deploy/base/bootstrap/cluster-baseline-settings/03-akv-secrets-store-csi.yaml, deploy/base/bootstrap/cluster-baseline-settings/05-kured.yaml, deploy/bootstrap-dev/cluster-baseline-settings/04-aad-pod-identity.yaml, deploy/bootstrap-pre/cluster-baseline-settings/04-aad-pod-identity.yaml, flux-init/init-preprod/gotk-repo.yaml
To update the cpu and memory resource
- Closes https://github.com/retaildevcrews/wcnp/issues/1015
- References https://github.com/retaildevcrews/wcnp/issues/1001
=> Update Memory and CPU for Cluster baseline settings

README.md, deploy/dev-ngsa-asb-eastus/istio/istio-ingress.yaml, deploy/dev-ngsa-asb-eastus/ngsa/namespace.yaml, deploy/dev-ngsa-asb-westus2/istio/istio-ingress.yaml, deploy/dev-ngsa-asb-westus2/ngsa/namespace.yaml, deploy/pre-ngsa-asb-centralus/istio/istio-ingress.yaml, deploy/pre-ngsa-asb-eastus/istio/istio-ingress.yaml, deploy/pre-ngsa-asb-westus2/istio/istio-ingress.yaml, templates/istio/istio-ingress.yaml
Adjust requests/limits for istio resources
Move sidecar injection to app specific level (eg: dev cosmos)
- Closes https://github.com/retaildevcrews/wcnp/issues/1016
=> Adjust limits for istiod, ingressgw and sidecars

README.md, docs/FluxDirStructure.md
Document Flux directory structure and show flowchart of flux application
- References https://github.com/retaildevcrews/wcnp/issues/1012
- References https://github.com/retaildevcrews/wcnp/pull/1034
=> Flux directory sturctuure documentation

README.md, docs/deployFrontDoor.md, spikes/front-door/setup-front-door.md, spikes/front-door/setup-frontdoor.sh
Added Azure CLI instructions to set up and configure Azure Front Door in NGSA-ASB environments. Current deployments were created manually in the portal.
- Closes retaildevcrews/wcnp/issues/1006
=> Added Azure Front Door setup instructions

spikes/cosmos-rbac/rbac_cosmos_in_aks.md
Added Spike documentation describing how to enable NGSA to connect to CosmosDB using RBAC
- Closes retaildevcrews/wcnp/issues/735
=> Instructions to disable cosmos keys, enable RBAC to connect to CosmosDB

deploy/dev-ngsa-asb-eastus/fluentbit/kustomization.yaml, deploy/dev-ngsa-asb-westus2/fluentbit/kustomization.yaml, deploy/pre-ngsa-asb-centralus/fluentbit/kustomization.yaml, deploy/pre-ngsa-asb-eastus/fluentbit/kustomization.yaml, deploy/pre-ngsa-asb-westus2/fluentbit/kustomization.yaml
Fluentbit configmap zone and region patches were not being applied by kustomization due to a mismatch between resource names in kustomization YAML files and the base app YAML file. The resource names have been updated to match each other.
- Closes retaildevcrews/wcnp/issues/1057
=> updated fluentbit configmaps

README.md, saveenv.sh
Save Hub and Spoke Variables Into Separate Files For Easier Context Switching
- Closes https://github.com/retaildevcrews/wcnp/issues/1071
=> Save Spoke Env Variables Into Separate Files

deploy/dev-ngsa-asb-eastus/monitoring/thanos/thanos-patch.yaml, deploy/pre-ngsa-asb-eastus/monitoring/thanos/thanos-patch.yaml
Redoing PR# https://github.com/retaildevcrews/ngsa-asb/pull/161
=> Fixed thanos WestUS3 url

spikes/harbor/README.md, spikes/harbor/harbor-virtual-svc.yaml, spikes/harbor/helm-values.yaml
We're deploying Harbor to our new cluster, to achieve parity.
Since we've changed our domain from cse.ms to austinrdc.dev, we're updating the Harbor documentation.
Hence, we needed to update our docs.
- Update Harbor URL from `cse.ms` to `austinrdc.dev`
- Change `tags` and `repository` link pointing to new ACR in new sub
- Update steps to integrate AAD Login via OIDC
- Closes https://github.com/retaildevcrews/wcnp/issues/1111
=> Update Harbor URL and Integrate AAD via OIDC

spikes/image-versioning/imageAutomation.md, spikes/image-versioning/ngsa/ngsa-memory.yaml
To demonstrate a spike for image versioning
- Closes https://github.com/retaildevcrews/wcnp/issues/1041
=> Added spike instructions for image automation

docs/renewCertificates.md
To add instructions on how to renew ssl certificates
- Closes https://github.com/retaildevcrews/wcnp/issues/1094
=> Added documentation on how to renew ssl certs

deploy/dev-ngsa-asb-eastus/ngsa/ngsa-pod-identity.yaml, deploy/dev-ngsa-asb-westus2/ngsa/ngsa-pod-identity.yaml, deploy/pre-ngsa-asb-centralus/ngsa/ngsa-pod-identity.yaml, deploy/pre-ngsa-asb-eastus/ngsa/ngsa-pod-identity.yaml, deploy/pre-ngsa-asb-westus2/ngsa/ngsa-pod-identity.yaml
Rename AzureIdentity and AzureIdentityBinding for ngsa pod identity
- Closes https://github.com/retaildevcrews/wcnp/issues/1125
=> Rename ngsa managed identity in deployment files

deploy/base/apps/istio/istio-ingress.yaml, deploy/base/bootstrap/cluster-baseline-settings/03-akv-secrets-store-csi.yaml, deploy/base/bootstrap/cluster-baseline-settings/04-aad-pod-identity.yaml, deploy/base/bootstrap/cluster-baseline-settings/05-kured.yaml, flux-init/base/gotk-components.yaml, templates/flux-v1-legacy.yaml, templates/istio/istio-ingress.yaml, templates/loderunner/loderunner-api.yaml, templates/loderunner/loderunner-clientmode.yaml, templates/loderunner/loderunner-ui.yaml, templates/monitoring/grafana/05-grafana.yaml, templates/ngsa/ngsa-cosmos.yaml, templates/ngsa/ngsa-java.yaml, templates/ngsa/ngsa-memory.yaml
- References https://github.com/retaildevcrews/wcnp/issues/1152
=> Update NodeSelector to use Node Type

scripts/ResourceAutomation/automationAccount.bicep
- Closes https://github.com/retaildevcrews/wcnp/issues/1165
- References https://github.com/retaildevcrews/ngsa-asb/pull/180
=> Updated firewall Schedule name

scripts/ResourceAutomation/automationAccount.bicep
Update job schedule names to new unique ones
- Closes https://github.com/retaildevcrews/wcnp/issues/1167
=> Update job schedule names to new unique ones

spikes/argo-cd/README.md, spikes/argo-cd/deploy/ngsa.yaml, spikes/argo-cd/manifests/application-set-sample.yaml, spikes/argo-cd/manifests/argo-ngsa-app.yaml
To introduce some documentation on how to get started using ArgoCD
- Closes https://github.com/retaildevcrews/wcnp/issues/1157
=> ArgoCD spike implementation

spikes/argo-workflow/README.md, spikes/argo-workflow/charts/loderunner/.helmignore, spikes/argo-workflow/charts/loderunner/Chart.yaml, spikes/argo-workflow/charts/loderunner/templates/NOTES.txt, spikes/argo-workflow/charts/loderunner/templates/_helpers.tpl, spikes/argo-workflow/charts/loderunner/templates/check-dependencies-configmap.yaml, spikes/argo-workflow/charts/loderunner/templates/check-dependencies-job.yaml, spikes/argo-workflow/charts/loderunner/templates/check-dependencies.yaml, spikes/argo-workflow/charts/loderunner/templates/deployment.yaml, spikes/argo-workflow/charts/loderunner/templates/service.yaml, spikes/argo-workflow/charts/loderunner/values.yaml, spikes/argo-workflow/charts/ngsa-memory/.helmignore, spikes/argo-workflow/charts/ngsa-memory/Chart.yaml, spikes/argo-workflow/charts/ngsa-memory/templates/NOTES.txt, spikes/argo-workflow/charts/ngsa-memory/templates/_helpers.tpl, spikes/argo-workflow/charts/ngsa-memory/templates/deployment.yaml, spikes/argo-workflow/charts/ngsa-memory/templates/service.yaml, spikes/argo-workflow/charts/ngsa-memory/values.yaml, spikes/argo-workflow/manifests/argo-workflow.yaml, spikes/argo-workflow/manifests/clusterrole.yaml, spikes/argo-workflow/manifests/clusterrolebinding.yaml, spikes/argo-workflow/manifests/serviceaccount.yaml
To provide a step by step spike demo around Argo Workflows
- Closes https://github.com/retaildevcrews/wcnp/issues/1229
- References #issue_number (this references the issue but does not close with PR)
=> Argo Workflow Spike

spikes/argo-workflow/README.md, spikes/argo-workflow/manifests/events/eventbus.yaml, spikes/argo-workflow/manifests/events/sensor-rbac.yaml, spikes/argo-workflow/manifests/events/webhook-event-source.yaml, spikes/argo-workflow/manifests/events/webhook-sensor.yaml, spikes/argo-workflow/manifests/events/workflow-rbac.yaml
To introduce instruction on how to run a sample Argo Event
- Closes https://github.com/retaildevcrews/wcnp/issues/1182
=> Argo Events Spike
